[tool.poetry]
name = "optiga"
version = "0.1.0"
description = ""
authors = ["horoiwa <horoiwa195@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.17"
pandas = "^0.25.3"
deap = "^1.3"
julia = "^0.5.0"
dataclasses_json = "^0.3.6"
numba = "^0.46.0"
matplotlib = "^3.1.2"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.scripts]
main = "tests.test_optiga:main"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

